### ISSUE TITLE
Trouble with the tutorial

### ISSUE THREAD

**Issue by Boldie** [parkouss/funq#20]
Hi,
I am trying to use the funq framework, unfortunately I struggle with the first steps, after installing from pip,  funq told me an invalid syntax, do you have a suggestion for me?

SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/usr/local/bin/funq", line 9, in <module>
    load_entry_point('funq-server==1.1.4', 'console_scripts', 'funq')()
  File "/usr/local/lib/python3.2/dist-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.2/dist-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.2/dist-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/usr/local/lib/python3.2/dist-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.2/dist-packages/funq_server/runner.py", line 68
    desc = u"""Start a QT application with a libFunq server injected."""
                                                                       ^
SyntaxError: invalid syntax

**Comment by Boldie** [comment]
Ok, found the problem, unlike stated funq is not compatible with python 3, because u"string" is no longer python code, the u needs to be removed. In python 3.3 it is back. So funq can not be used with python < 3.3.

**Comment by parkouss** [comment]
You're right, thanks for the report! We should say it in the documentation (at least README.md), and also ensure the version in the setup.py file.

I'm totally open to a PR if you have the time @Boldie !
